version: '2'


networks:
  app-tier:
    driver: bridge

services:
  service:
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9008:9008"
    environment:
      KV_TYPE: redis
      REDIS_READ_ONLY: "false"
      REDIS_SENTINEL_HOSTS: redis-sentinel:26379
    networks:
      - app-tier
    depends_on:
      - redis-sentinel
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    ports:
      - '6379'
  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379'
    depends_on:
      - redis
    networks:
      - app-tier
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=5

    depends_on:
      - redis
      - redis-slave
    ports:
      - '26379-26381:26379'
    networks:
      - app-tier