version: "3.8"

networks:
  campaigns-network:
    driver: bridge

services:
  campaigns-service:
    build:
      context: .
    container_name: campaigns-service
    image: campaignsservice:latest
    environment:
      - SQL_CONNECTION=postgresql://postgres-database:5432/postgres?user=postgres&password=admin&sslmode=disable
    depends_on:
      postgres-database:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "9008:9008"
    links:
      - postgres-database
    networks:
      - campaigns-network
  postgres-database:
    container_name: postgres-campaigns-service
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - ./_postgres-db:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - campaigns-network
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    networks:
      - campaigns-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@blockwallet.io
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres-database

volumes:
  postgres-db:
    driver: local
