GO ?= go
GOBUILD ?= $(GO) build
GOINSTALL ?= $(GO) install
GOGET ?= $(GO) get
GOMOD ?= $(GO) mod
GORUN ?= $(GO) run
GOTEST ?= $(GO) test
GOTOOL ?= $(GO) tool
GODOC ?= godoc
GOCONVEY ?= goconvey

GOIMPORTS := $(GORUN) golang.org/x/tools/cmd/goimports
PROTOTOOL := $(GORUN) github.com/uber/prototool/cmd/prototool
GOLINT := $(GORUN) github.com/golangci/golangci-lint/cmd/golangci-lint