// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CounterMetricSender is an autogenerated mock type for the CounterMetricSender type
type CounterMetricSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: labels
func (_m *CounterMetricSender) Send(labels map[string]string) {
	_m.Called(labels)
}
