// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// LatencyMetricSender is an autogenerated mock type for the LatencyMetricSender type
type LatencyMetricSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: start, end, labels
func (_m *LatencyMetricSender) Send(start time.Time, end time.Time, labels map[string]string) {
	_m.Called(start, end, labels)
}
