// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RequestLatencyMetricSender is an autogenerated mock type for the RequestLatencyMetricSender type
type RequestLatencyMetricSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: start, end, method, req, err
func (_m *RequestLatencyMetricSender) Send(start time.Time, end time.Time, method string, req interface{}, err error) {
	_m.Called(start, end, method, req, err)
}
